"""
Tests for point cloud (LAS/LAZ) support in geoextent.

LAS/LAZ files are handled by the handle_pointcloud module using laspy.
Bounding boxes are extracted from file headers (no point data loading).
Temporal extent comes from the LAS header creation date field.

Test data is generated by tests/testdata/pointcloud/generate_test_data.py.
"""

import os
import geoextent.lib.extent as geoextent
from geoextent.lib import handle_pointcloud, handle_raster, handle_vector
from help_functions_test import tolerance
import pytest


class TestPointCloudBoundingBox:
    """Test bounding box extraction from point cloud files"""

    def test_las_wgs84_bbox(self):
        """Extract bounding box from WGS84 LAS file.

        Test data: 5 points near Munster, Germany.
        Internal bbox: [7.5, 51.9, 7.7, 52.0] (lon/lat)
        Output bbox: [51.9, 7.5, 52.0, 7.7] (lat/lon, EPSG:4326 native order)
        """
        result = geoextent.from_file("tests/testdata/pointcloud/wgs84.las", bbox=True)
        assert result is not None
        assert "bbox" in result
        assert "crs" in result
        assert result["crs"] == "4326"
        # Output is in EPSG:4326 native order: [minlat, minlon, maxlat, maxlon]
        assert result["bbox"] == pytest.approx([51.9, 7.5, 52.0, 7.7], abs=tolerance)

    def test_las_utm32n_bbox(self):
        """Extract bounding box from UTM 32N LAS file with CRS transform.

        Test data: 5 points in UTM 32N (EPSG:32632), near Munster.
        Coordinates should be transformed to WGS84 in output.
        """
        result = geoextent.from_file("tests/testdata/pointcloud/utm32n.las", bbox=True)
        assert result is not None
        assert "bbox" in result
        assert "crs" in result
        assert result["crs"] == "4326"
        # Transformed UTM coordinates should be roughly in the Munster area
        bbox = result["bbox"]
        # bbox in [minlat, minlon, maxlat, maxlon] order
        assert 51.0 < bbox[0] < 53.0  # min latitude
        assert 7.0 < bbox[1] < 8.0  # min longitude
        assert 51.0 < bbox[2] < 53.0  # max latitude
        assert 7.0 < bbox[3] < 8.0  # max longitude

    def test_las_no_crs(self):
        """LAS file without CRS but coordinates in WGS84 bounds.

        When no CRS is embedded, coordinates within WGS84 bounds are
        assumed to be WGS84.
        """
        result = geoextent.from_file("tests/testdata/pointcloud/no_crs.las", bbox=True)
        assert result is not None
        assert "bbox" in result
        assert result["crs"] == "4326"
        assert result["bbox"] == pytest.approx([51.9, 7.5, 52.0, 7.7], abs=tolerance)

    def test_las_empty_file(self):
        """Empty LAS file (0 points) returns no bounding box."""
        result = geoextent.from_file("tests/testdata/pointcloud/empty.las", bbox=True)
        assert result is not None
        assert result.get("bbox") is None

    def test_laz_bbox(self):
        """Extract bounding box from compressed LAZ file.

        LAZ files should produce the same result as the corresponding LAS.
        """
        result = geoextent.from_file("tests/testdata/pointcloud/wgs84.laz", bbox=True)
        assert result is not None
        assert "bbox" in result
        assert "crs" in result
        assert result["crs"] == "4326"
        assert result["bbox"] == pytest.approx([51.9, 7.5, 52.0, 7.7], abs=tolerance)

    def test_las_wgs84_bbox_legacy(self):
        """Bounding box in legacy [lon, lat] order."""
        result = geoextent.from_file(
            "tests/testdata/pointcloud/wgs84.las", bbox=True, legacy=True
        )
        assert result is not None
        # Legacy order: [minlon, minlat, maxlon, maxlat]
        assert result["bbox"] == pytest.approx([7.5, 51.9, 7.7, 52.0], abs=tolerance)


class TestPointCloudTemporalExtent:
    """Test temporal extent extraction from point cloud files"""

    def test_las_temporal_extent(self):
        """Extract creation date from LAS header."""
        result = geoextent.from_file("tests/testdata/pointcloud/wgs84.las", tbox=True)
        assert result is not None
        assert "tbox" in result
        assert result["tbox"] == ["2023-06-15", "2023-06-15"]

    def test_las_temporal_extent_utm(self):
        """Extract creation date from UTM LAS file."""
        result = geoextent.from_file("tests/testdata/pointcloud/utm32n.las", tbox=True)
        assert result is not None
        assert "tbox" in result
        assert result["tbox"] == ["2024-01-10", "2024-01-10"]

    def test_las_no_temporal(self):
        """LAS file without creation date returns no temporal extent."""
        result = geoextent.from_file("tests/testdata/pointcloud/no_crs.las", tbox=True)
        assert result is not None
        assert result.get("tbox") is None

    def test_las_temporal_custom_format(self):
        """Temporal extent with custom time format."""
        result = geoextent.from_file(
            "tests/testdata/pointcloud/wgs84.las",
            tbox=True,
            time_format="iso8601",
        )
        assert result is not None
        assert "tbox" in result
        assert result["tbox"] == ["2023-06-15T00:00:00Z", "2023-06-15T00:00:00Z"]


class TestPointCloudFormatMetadata:
    """Test format and handler metadata in extraction results"""

    def test_pointcloud_format_metadata(self):
        """Check format and handler metadata for LAS files."""
        result = geoextent.from_file("tests/testdata/pointcloud/wgs84.las", bbox=True)
        assert result is not None
        assert result["format"] == "las"
        assert result["geoextent_handler"] == "handle_pointcloud"

    def test_laz_format_metadata(self):
        """Check format metadata for LAZ files."""
        result = geoextent.from_file("tests/testdata/pointcloud/wgs84.laz", bbox=True)
        assert result is not None
        assert result["format"] == "laz"
        assert result["geoextent_handler"] == "handle_pointcloud"


class TestPointCloudHandlerConflicts:
    """Test that LAS/LAZ files are not claimed by other handlers"""

    def test_las_not_handled_by_raster(self):
        """LAS files should not be claimed by the raster handler."""
        assert not handle_raster.check_file_supported(
            "tests/testdata/pointcloud/wgs84.las"
        )

    def test_las_not_handled_by_vector(self):
        """LAS files should not be claimed by the vector handler."""
        assert not handle_vector.check_file_supported(
            "tests/testdata/pointcloud/wgs84.las"
        )

    def test_pointcloud_handler_claims_las(self):
        """The pointcloud handler should claim LAS files."""
        assert handle_pointcloud.check_file_supported(
            "tests/testdata/pointcloud/wgs84.las"
        )

    def test_pointcloud_handler_claims_laz(self):
        """The pointcloud handler should claim LAZ files."""
        assert handle_pointcloud.check_file_supported(
            "tests/testdata/pointcloud/wgs84.laz"
        )

    def test_pointcloud_handler_rejects_geojson(self):
        """The pointcloud handler should reject non-LAS files."""
        assert not handle_pointcloud.check_file_supported(
            "tests/testdata/muenster_ring_zeit.geojson"
        )


class TestPointCloudInDirectory:
    """Test that LAS files are discovered during directory scanning"""

    def test_pointcloud_in_directory(self):
        """Directory scanning picks up LAS files."""
        result = geoextent.from_directory(
            "tests/testdata/pointcloud",
            bbox=True,
            tbox=True,
            details=True,
            show_progress=False,
        )
        assert result is not None
        assert "bbox" in result
        assert "tbox" in result
        # Should have found at least one file with an extent
        assert result["bbox"] is not None
        # Check details for individual files
        details = result.get("details", {})
        assert any(k.endswith(".las") or k.endswith(".laz") for k in details.keys())


class TestPointCloudBboxAndTbox:
    """Test combined bbox + tbox extraction"""

    def test_las_bbox_and_tbox(self):
        """Extract both bbox and tbox from a single LAS file."""
        result = geoextent.from_file(
            "tests/testdata/pointcloud/wgs84.las", bbox=True, tbox=True
        )
        assert result is not None
        assert "bbox" in result
        assert "tbox" in result
        assert result["crs"] == "4326"
        assert result["bbox"] == pytest.approx([51.9, 7.5, 52.0, 7.7], abs=tolerance)
        assert result["tbox"] == ["2023-06-15", "2023-06-15"]
